In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('color.csv')
df

Brightness  Saturation class
0          40          20   Red
1          50          50  Blue
2          60          90  Blue
3          10          25   Red
4          70          70  Blue
5          60          10   Red
6          25          80  Blue

In [2]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [3]:
X = df[['Brightness','Saturation']]
y = df['class']

In [4]:
from sklearn.preprocessing import LabelEncoder
label_encod = LabelEncoder()
y = label_encod.fit_transform(y)
y

array([1, 0, 0, 1, 0, 1, 0])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

Brightness  Saturation
5          60          10
2          60          90
4          70          70
3          10          25
6          25          80

In [6]:
X_test

Brightness  Saturation
0          40          20
1          50          50

In [7]:
y_train

array([1, 0, 0, 1, 0])

In [8]:
y_test

array([1, 0])

In [9]:
from sklearn.neighbors import KNeighborsClassifier
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
y_pred

C:\Users\donsh\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0])

In [10]:
from sklearn.metrics import accuracy_score 
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy : ", accuracy)

Accuracy :  1.0


In [11]:
new_data = pd.DataFrame({
    'Brightness':[55,25],
    'Saturation':[30,70]
})
new_pred = knn.predict(new_data)
new_pred_decoded = label_encod.inverse_transform(new_pred)
new_pred_decoded

C:\Users\donsh\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array(['Red', 'Blue'], dtype=object)

In [12]:
for i, prediction in enumerate(new_pred_decoded):
    print(f"sample{i+1}: Predicted class is {prediction}")

sample1: Predicted class is Red
sample2: Predicted class is Blue
